feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path("details/<int:pk>/", PostDetailView.as_view(), name="postdetailsview"),
    path("post/", AddPostView.as_view(), name="post")
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=150, blank=False, null=False)
    image = ImageField()

    def __str__(self):
        return self.title
    
    

feed/forms.py
from django import forms


class Postform(forms.Form):

    title = forms.CharField(label='Add a title')
    image = forms.FileField(label='Upload Image')

feed/views.py
from django.views.generic import TemplateView, DetailView, FormView
from .models import Post
from .forms import Postform
from django.contrib import messages


class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.all().order_by('-id')
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'details.html'


class AddPostView(FormView):
    template_name = 'new_post.html'
    form_class = Postform
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):

        new_object = Post.objects.create(
            title=form.cleaned_data['title'],
            image=form.cleaned_data['image'],

        )
        messages.add_message(self.request, messages.SUCCESS,
                             'Post Upload successfully')

        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}Defoult Title{% endblock title %}</title>
  </head>
  {% include 'include/naver.html' %}
  <body>
    {% block body %}{% endblock body %}
  </body>
</html>

templates/details.html
{% extends "base.html" %} 
{% block title %} Post Details Page
{% endblock title%} 

{% block body %}
<a href="{% url 'feed:index' %}"> Go Back</a>
<h3>{{object.title}}</h3>
<img src="{{object.image.url}}" height=400px width=400px crop="center" alt="">
{% endblock body %}

templates/home.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
   Home
{% endblock title %}
    

{% block body %}
{% if messages %}
        
            {% for message in messages %}
             <div class="bg-{% if message.tags %}{{message.tags}}{% endif %} bg-gradient">{{ message }}</div>
            {% endfor %}
        
{% endif %}
<div class="row">
        
        {% for post in posts %}
            <div class="col-sm-6 col-md-3 p-2">
                <div class="card" style="width: 18rem;">
                    {% thumbnail post.image "200x200" crop="center" as im %}
                <img src="{{ im.url }}." class="card-img-top" alt="...">
                {% endthumbnail %}
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="{% url 'feed:postdetailsview' post.id  %}" class="btn btn-primary">Go Detais</a>
                    </div>
                </div>
            </div>
        {% endfor %}
</div>
{% endblock body %}

templates/include/naver.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="/">Post Blog</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'feed:post' %}">Add a post</a>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/new_post.html
{% extends 'base.html' %}


{% block body %}
    <div class="container mt-5">
    <form action=""  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-success">Submit Post</button>
    </form>   
    </div>
{% endblock body %}
    